<template><div><h1 id="rxjs" tabindex="-1"><a class="header-anchor" href="#rxjs" aria-hidden="true">#</a> RxJs</h1>
<h2 id="函数式编程和响应式编程" tabindex="-1"><a class="header-anchor" href="#函数式编程和响应式编程" aria-hidden="true">#</a> 函数式编程和响应式编程</h2>
<h3 id="响应式编程" tabindex="-1"><a class="header-anchor" href="#响应式编程" aria-hidden="true">#</a> 响应式编程</h3>
<p><strong>响应式编程</strong>，Reactive Programing，又称反应式编程，简称 RP，一种面向<code v-pre>数据流</code>、<code v-pre>变化传播</code>、实现<code v-pre>异步编程</code>的编程范式。这意味着可以在编程语言中很方便地表达静态或动态的数据流，而相关的计算模型会自动将变化的值通过数据流进行传播。数据流可以接受一个，甚至多个。而响应式就是从数据流中过滤、组合等操作出你感兴趣的以生成一个新的数据流，还可以把一个流中的数据值映射到一个新的数据流中。</p>
<p>它的<code v-pre>变化传播</code>在于一个数据流经过一串操作转化为另一个数据流，然后分发给各个订阅者的过程。它的<code v-pre>异步编程</code>在于数据流被分发到各个订阅者前对数据进行特殊处理，订阅者根据数据处理后响应新的数据流</p>
<h3 id="函数式编程" tabindex="-1"><a class="header-anchor" href="#函数式编程" aria-hidden="true">#</a> 函数式编程</h3>
<p>强调使用函数来解决问题的一种编程方式。主要有以下特点</p>
<p>函数为必须为声明式</p>
<p>函数必须为纯函数： 函数执行过程完全由输入参数决定，不会受参数之外的任何数据影响。不会修改任何外部的全局变量或传入的参数对象。</p>
<p>数据不可变性：不修改原来数据，产生新的数据来作运算结果。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// 函数为声明式</span>
<span class="token keyword">const</span> <span class="token function-variable function">double</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">arr</span><span class="token punctuation">)</span><span class="token operator">=></span>arr<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">item</span><span class="token operator">:</span>number</span><span class="token punctuation">)</span><span class="token operator">=></span>item<span class="token operator">*</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">addOne</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">arr</span><span class="token punctuation">)</span><span class="token operator">=></span>arr<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">item</span><span class="token operator">:</span>number</span><span class="token punctuation">)</span><span class="token operator">=></span>item<span class="token operator">+</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> <span class="token function-variable function">arrPush1</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">data</span><span class="token operator">:</span> Array<span class="token operator">&lt;</span>number<span class="token operator">></span><span class="token punctuation">,</span> <span class="token literal-property property">addNum</span><span class="token operator">:</span> number</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
<span class="token comment">// 改变了外部变量，违反了纯函数的规则</span>
    data<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>addNum<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> data<span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">arrPush2</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">data</span><span class="token operator">:</span> Array<span class="token operator">&lt;</span>number<span class="token operator">></span><span class="token punctuation">,</span> <span class="token literal-property property">addNum</span><span class="token operator">:</span> number</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
<span class="token comment">// 产生新数据</span>
   <span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token operator">...</span>data<span class="token punctuation">,</span> addNum<span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> initData <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> doubleArr1 <span class="token operator">=</span> <span class="token function">arrPush1</span><span class="token punctuation">(</span>initData<span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> printArr1 <span class="token operator">=</span> <span class="token function">double</span><span class="token punctuation">(</span>doubleArr1<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// [2,4,6,8]</span>
<span class="token comment">// initData = [1,2,3,4]</span>

<span class="token keyword">const</span> doubleArr2 <span class="token operator">=</span> <span class="token function">arrPush2</span><span class="token punctuation">(</span>initData<span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> printArr2 <span class="token operator">=</span> <span class="token function">double</span><span class="token punctuation">(</span>doubleArr2<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// [2,4,6,8,8]</span>
<span class="token comment">// initData=[1,2,3]</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="发布订阅模式" tabindex="-1"><a class="header-anchor" href="#发布订阅模式" aria-hidden="true">#</a> 发布订阅模式</h2>
</div></template>
